name: greedymax-env
dependencies:
  - python=3.9.*
  - astropy
  - hypothesis
  - joblib
  - marshmallow_dataclass
  - marshmallow_enum
  - marshmallow_numpy
  - matplotlib
  - numpy=1.21.*
  - openpyxl
  - pytest
  - pytz
  - tabulate
  - tqdm
