  name: Run Scripts
  on: push
  jobs:
    run:
      runs-on: ubuntu-latest
      environment: schedule-staging
      timeout-minutes: 30

      steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        # Setup Python (faster than using Python container)
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          env:
            GH_PAT: ${{ secrets.GH_PAT }}

        - name: Add $PYTHONPATH
          run: echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/scheduler/scheduler" >> $GITHUB_ENV

        - name: Run Greedymax
          env:
            REDISCLOUD_URL: ${{ secrets.REDISCLOUD_URL }}
            GPP_URL: ${{ secrets.GPP_URL }}
            GPP_KEY: ${{ secrets.GPP_KEY }}
          run: python scheduler/scripts/run_greedymax.py
