  name: Run Scripts
  on: push
  jobs:
    run:
      runs-on: ubuntu-latest
      environment: schedule-staging
      timeout-minutes: 30

      steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        # Setup Python (faster than using Python container)
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Add $PYTHONPATH
          run: echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/scheduler/scheduler:/home/runner/work/scheduler/scheduler/pyexplore/pyexplore" >> $GITHUB_ENV

        - name: Clone pyexplore
          env:
            GH_PAT: ${{ secrets.GH_PAT }}
          run: |
              git clone https://${GH_PAT}@github.com/stroncod/pyexplore.git

        - name: Install requirements for pyexplore
          run: |
            pip install -r pyexplore/requirements.txt
        - name: Install pyexplore as package
          run: cd pyexplore/pyexplore && pip install -e .

        - name: Run Greedymax
          env:
            REDISCLOUD_URL: ${{ secrets.REDISCLOUD_URL }}
          run: python scheduler/scripts/run_greedymax.py
