  name: Run Scripts
  on: push
  jobs:
    run:
      runs-on: ubuntu-latest
      environment: schedule-staging
      timeout-minutes: 30

      steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        # Setup Python (faster than using Python container)
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Add $PYTHONPATH
          run: echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/scheduler/scheduler:/home/runner/work/scheduler/scheduler/pyexplore/pyexplore" >> $GITHUB_ENV

        - name: Install pyexplore
          env:
            GH_PAT: ${{ secrets.GH_PAT }}
          run: |
              pip install git+https://${GH_PAT}@github.com/stroncod/pyexplore.git
        - name: List secrets
          run: |
                  echo "$ALLMYSECRETS"
                  echo "$ALLMYVARS"
                  shell: bash
                  env:
                    ALLMYSECRETS: ${{ toJSON(secrets) }}
                    ALLMYVARS: ${{ toJSON(vars) }}

        - name: Run Greedymax
          env:
            REDISCLOUD_URL: ${{ secrets.REDISCLOUD_URL }}
          run: python scheduler/scripts/run_greedymax.py
